### ISSUE TITLE
Possible to move scroll of parent to bottom of iframe?

### ISSUE THREAD

**Issue by crdunst** [Lemick/open-iframe-resizer#5]
Hi, just to echo a previous user, thanks for creating this open source alternative, it works great.

It's a bit of a long shot, but is there any way to preserve the location of the parent scroll?  We have a child page that varies in length as you work through a multi-page form.

If, for example, our users are on page 2 of the form, the height of the iframe is quite long.  They then click 'next' to go to page 3, and the iframe goes much shorter in height (which is great, the resizer is working brilliantly).  The problem is however, the user on the parent page is now positioned much further below the iframe, and it's disorientating. 

Ideally, the parent scroll would adjust to keep the iframe in view.  Hope that makes sense?  We can access parent and child, so if there's a fix for this, that's be fantastic.

**Comment by Lemick** [comment]
Hi, thanks, I think I see the idea, that seems like a feature other people may need, I will take a look at it 👍

**Comment by Lemick** [comment]
Just released a [new version](https://github.com/Lemick/open-iframe-resizer/releases/tag/v1.2.0) containing a new `onIframeResize` setting and an `updateParentScrollOnResize` function for your specific use-case. I prefer not to make this a default because excessive scrolling can be annoying for the user.

Can you try it out to see if it works?

**Comment by crdunst** [comment]
I really appreciate it, thanks.  Will try it out and report back.

**Comment by Lemick** [comment]
Thanks, yes the CDN latest version is taking a little time to update.. Maybe use this instead
`https://cdn.jsdelivr.net/npm/@open-iframe-resizer/core@v1.2.0/dist/index.min.js`

**Comment by crdunst** [comment]
The CDN latest version has updated and I tested it out, it's working perfectly, thanks so much for the edit and updates, much appreciated.
