### ISSUE TITLE
Support SSR?

### ISSUE THREAD

**Issue by masontmorrow** [Lemick/open-iframe-resizer#7]
I'm using a NextJS application with SSR. On build, all client side APIs are undefined of course, but those references break the build. Are there plans to support SSR builds in the future? Thanks

**Comment by Lemick** [comment]
Yes indeed, I haven’t tested it in an SSR environment, I’ll take a look at it.

**Comment by Lemick** [comment]
I released a new version, you can test it 😄

**Comment by masontmorrow** [comment]
Yes, everything works as expected. Thanks!
